Repository opendatahub-io/odh-model-controller, pull requests merged in 2023-08, with the labels that each got.

#62 Add AWS_CA_BUNDLE for storage-config and fix opendatahub.io/managed=false behavior
  controllers/storageconfig_controller.go
  controllers/storageconfig_controller_test.go
  controllers/suite_test.go
  controllers/testdata/secrets/dataconnection-encoded.yaml
  controllers/testdata/secrets/dataconnection-string.yaml
  controllers/testdata/secrets/storageconfig-encoded-unmanaged.yaml
  controllers/testdata/secrets/storageconfig-encoded.yaml
  controllers/testdata/secrets/storageconfig-string-unmanaged.yaml
  controllers/testdata/secrets/storageconfig-string.yaml
Labels: approved, lgtm

#65 add monitoring controller for kserve and istio metrics
  config/crd/external/monitoring.coreos.com_podmonitors.yaml
  config/crd/external/security.istio.io_peerauthentications.yaml
  config/crd/external/telemetry.istio.io_telemetries.yaml
  config/rbac/kserve_prometheus_clusterrole.yaml
  config/rbac/role.yaml
  controllers/inferenceservice_controller.go
  controllers/kserve_inferenceservice_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, do-not-merge/work-in-progress

#66 Merge pull request #65 from VedantMahabaleshwarkar/kserve-metrics
  config/crd/external/monitoring.coreos.com_podmonitors.yaml
  config/crd/external/security.istio.io_peerauthentications.yaml
  config/crd/external/telemetry.istio.io_telemetries.yaml
  config/rbac/kserve_prometheus_clusterrole.yaml
  config/rbac/role.yaml
  controllers/inferenceservice_controller.go
  controllers/kserve_inferenceservice_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm

#68 fix the need to have istio crds for modelmesh reconciliation
  controllers/inferenceservice_controller.go
  controllers/kserve_inferenceservice_controller.go
  controllers/suite_test.go
Labels: approved

#70 Merge pull request #68 from VedantMahabaleshwarkar/crd_fix
  controllers/inferenceservice_controller.go
  controllers/kserve_inferenceservice_controller.go
  controllers/suite_test.go
Labels: approved

#76 remove check for istio CRD installation
  controllers/kserve_inferenceservice_controller.go
Labels: approved, lgtm

#77 remove check for istio CRD installation
  controllers/kserve_inferenceservice_controller.go
Labels: approved, lgtm
