Repository opendatahub-io/odh-model-controller, pull requests merged in 2024-01, with the labels that each got.

#136 fix: Remove NetworkPolicies created to relax SMCP policies
  controllers/reconcilers/kserve_inferenceservice_reconciler.go
  controllers/reconcilers/kserve_networkpolicy_reconciler.go
Labels: approved, lgtm

#139 Fixes CVE-2023-48795
  go.mod
  go.sum
Labels: approved, lgtm

#140 Fixes vulnerabilities on the otelhttp dependency
  go.mod
Labels: approved, lgtm

#141 Update knative-serving
  go.mod
  go.sum
Labels: approved, lgtm

#142 Fix Stack-based Buffer Overflow on protobuf
  go.mod
  go.sum
Labels: approved, lgtm

#138 [Cherry-pick] fix: Remove NetworkPolicies created to relax SMCP policies
  controllers/reconcilers/kserve_inferenceservice_reconciler.go
  controllers/reconcilers/kserve_networkpolicy_reconciler.go
Labels: approved, lgtm

#143 Revert "fix: Remove NetworkPolicies created to relax SMCP policies"
  controllers/reconcilers/kserve_inferenceservice_reconciler.go
  controllers/reconcilers/kserve_networkpolicy_reconciler.go
Labels: approved, lgtm

#144 Revert "[Cherry-pick] fix: Remove NetworkPolicies created to relax SMCP policies"
  controllers/reconcilers/kserve_inferenceservice_reconciler.go
  controllers/reconcilers/kserve_networkpolicy_reconciler.go
Labels: approved, lgtm

#148 add back rbac removed by linter
  config/rbac/role.yaml
Labels: approved, lgtm

#149 add back rbac removed by linter
  config/rbac/role.yaml
Labels: approved, lgtm

#146 add temp Job to delete old monitoring stack
  config/overlays/odh/kustomization.yaml
  config/overlays/odh/remove-deprecated-monitoring.yaml
  config/rbac/role.yaml
Labels: approved, lgtm

#145 fix: adds network policies to unblock traffic between components
  controllers/kserve_inferenceservice_controller_test.go
  controllers/reconcilers/kserve_istio_peerauthentication_reconciler.go
  controllers/reconcilers/kserve_istio_podmonitor_reconciler.go
  controllers/reconcilers/kserve_istio_servicemonitor_reconciler.go
  controllers/reconcilers/kserve_metrics_servicemonitor_reconciler.go
  controllers/reconcilers/kserve_networkpolicy_reconciler.go
  controllers/suite_test.go
Labels: approved, lgtm

#151 add temp Job to delete old monitoring stack
  config/overlays/odh/kustomization.yaml
  config/overlays/odh/remove-deprecated-monitoring.yaml
  config/rbac/role.yaml
Labels: approved, lgtm

#152 [cherry-pick] fix: adds network policies to unblock traffic between components (#145)
  controllers/kserve_inferenceservice_controller_test.go
  controllers/reconcilers/kserve_istio_peerauthentication_reconciler.go
  controllers/reconcilers/kserve_istio_podmonitor_reconciler.go
  controllers/reconcilers/kserve_istio_servicemonitor_reconciler.go
  controllers/reconcilers/kserve_metrics_servicemonitor_reconciler.go
  controllers/reconcilers/kserve_networkpolicy_reconciler.go
  controllers/suite_test.go
Labels: lgtm

#153 RHOAIENG-1229 : Error in odh-model-controller logs on deletion of Mod…
  config/rbac/role.yaml
Labels: approved, lgtm

#156 Fixes Stack-based Buffer Overflow on protobuf
  go.mod
  go.sum
Labels: approved, lgtm

#157 Fixes knative.dev/serving Uncontrolled Resource Consumption
  go.mod
  go.sum
Labels: approved, lgtm

#26 relicense project to Apache 2.0
  LICENSE
Labels: approved, lgtm, ok-to-test

#158 Remove temporary job to delete old monitoring stack, and fix kubebuilder RBAC
  Makefile
  config/overlays/odh/kustomization.yaml
  config/overlays/odh/remove-deprecated-monitoring.yaml
  config/rbac/role.yaml
  hack/manifests_boilerplate.yaml.txt
  main.go
Labels: approved, lgtm
