Repository opendatahub-io/odh-model-controller, pull requests merged in 2024-02, with the labels that each got.

#159 update params pointing to v0.11.1.1
  config/base/params.env
Labels: approved, lgtm

#161 Update OWNERS in release branch
  OWNERS
Labels: approved, lgtm

#160 Update OWNERS in main branch
  OWNERS
Labels: approved, lgtm

#135 Implement model registry inference service reconciliation
  Makefile
  config/crd/external/kustomization.yaml
  config/overlays/dev/kustomization.yaml
  config/overlays/dev/odh_model_controller_manager_patch.yaml
  config/overlays/dev/params.env
  config/rbac/role.yaml
  controllers/comparators/inferenceservice_comparator.go
  controllers/constants/constants.go
  controllers/mr_inferenceservice_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
  test/config/kind-e2e-config.yaml
  test/data/deploy/inference-service-to-delete.yaml
  test/data/deploy/inference-service-with-model-version.yaml
  test/data/deploy/inference-service-without-model-version.yaml
  test/data/deploy/inference-service-without-registered-model.yaml
  test/data/deploy/kserve-openvino-serving-runtime-1.yaml
  test/data/model-registry/database_deployment.yaml
  test/data/model-registry/modelregistry_deployment.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/modelregistry_controller_e2e_test.go
  test/utils/utils.go
Labels: approved, lgtm, do-not-merge/hold

#163 Update references to image for ODH 2.8 release
  config/base/params.env
Labels: approved

#165 Bump model-registry to v0.1.1
  go.mod
  go.sum
  test/data/model-registry/modelregistry_deployment.yaml
Labels: approved, lgtm

#166 [Feature] Integrated OpenDataHub Centralized Custom Certificate
  controllers/constants/constants.go
  controllers/kserve_customcacert_controller.go
  controllers/kserve_customcacert_controller_test.go
  controllers/storageconfig_controller.go
  controllers/storageconfig_controller_test.go
  controllers/suite_test.go
  controllers/testdata/configmaps/odh-kserve-custom-ca-cert-configmap-updated.yaml
  controllers/testdata/configmaps/odh-kserve-custom-ca-cert-configmap.yaml
  controllers/testdata/configmaps/odh-trusted-ca-bundle-configmap-updated.yaml
  controllers/testdata/configmaps/odh-trusted-ca-bundle-configmap.yaml
  controllers/testdata/secrets/dataconnection-encoded.yaml
  controllers/testdata/secrets/dataconnection-string.yaml
  controllers/testdata/secrets/storageconfig-cert-encoded.yaml
  controllers/testdata/secrets/storageconfig-cert-string.yaml
  controllers/testdata/secrets/storageconfig-encoded.yaml
  controllers/testdata/secrets/storageconfig-string.yaml
  controllers/testdata/secrets/storageconfig-updated-cert-encoded.yaml
  controllers/testdata/secrets/storageconfig-updated-cert-string.yaml
  controllers/utils/utils.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm

#168 [Fix] for integration ca cert, role change needed
  config/rbac/role.yaml
Labels: approved, lgtm

#167 update a logic to find data connection list
  controllers/kserve_customcacert_controller.go
  controllers/storageconfig_controller.go
  controllers/storageconfig_controller_test.go
Labels: approved, lgtm

#164 support no reconciliation for rawdeployments
  controllers/inferenceservice_controller.go
  controllers/kserve_inferenceservice_controller_authconfig_test.go
  controllers/reconcilers/kserve_inferenceservice_reconciler.go
  controllers/reconcilers/mm_inferenceservice_reconciler.go
  controllers/utils/utils.go
Labels: approved, lgtm

#173 Update kubebuilder to update role.yaml
  config/rbac/role.yaml
  main.go
Labels: approved, lgtm

#174 [Cherry-Pick]Update kubebuilder to update role.yaml
  config/rbac/role.yaml
  main.go
Labels: approved, lgtm

#171 support no reconciliation for rawdeployments
  controllers/inferenceservice_controller.go
  controllers/reconcilers/kserve_inferenceservice_reconciler.go
  controllers/reconcilers/mm_inferenceservice_reconciler.go
  controllers/utils/utils.go
Labels: approved, lgtm
