Repository opendatahub-io/odh-model-controller, pull requests merged in 2024-06, with the labels that each got.

#210 Upgrade kserve version to v0.12.1 in odh-model-controller
  Containerfile
  controllers/inferenceservice_controller.go
  controllers/monitoring_controller.go
  controllers/suite_test.go
  controllers/webhook/ksvc_validator.go
  controllers/webhook_ksvc_validator_test.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm

#216 Cherry-pick : Upgrade kserve version to v0.12.1 in odh-model-controller
  Containerfile
  controllers/inferenceservice_controller.go
  controllers/monitoring_controller.go
  controllers/suite_test.go
  controllers/webhook/ksvc_validator.go
  controllers/webhook_ksvc_validator_test.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm

#207 [RHOAIENG-7484] - make container builder configurable for odh-control…
  Makefile
  README.md
Labels: approved, lgtm

#217 Fix performance issues in odh model controller
  main.go
Labels: approved, lgtm

#209 Adding JSON files for Prometheus queries for Runtimes.
  controllers/constants/ovms-metrics.json
  controllers/constants/tgis-metrics.json
  controllers/constants/vllm-metrics.json
Labels: approved, lgtm

#218 Add Caikit Standalone template
  config/base/kustomization.yaml
  config/base/params.env
  config/runtimes/caikit-standalone-template.yaml
  config/runtimes/kustomization.yaml
  controllers/constants/caikit-metrics.json
Labels: approved, lgtm, ok-to-test

#222 fix vllm template
  config/runtimes/caikit-tgis-template.yaml
  config/runtimes/tgis-template.yaml
  config/runtimes/vllm-template.yaml
Labels: approved, lgtm, ok-to-test

#223 [Cherry-pick] - fix vllm template
  config/runtimes/caikit-tgis-template.yaml
  config/runtimes/tgis-template.yaml
  config/runtimes/vllm-template.yaml
Labels: approved, lgtm

#220 Kserve Dashboard Reconciler
  Containerfile
  controllers/comparators/configmap_comparator.go
  controllers/constants/caikit-metrics.json
  controllers/constants/constants.go
  controllers/constants/ovms-metrics.json
  controllers/constants/tgis-metrics.json
  controllers/constants/vllm-metrics.json
  controllers/inferenceservice_controller.go
  controllers/reconcilers/kserve_metrics_dashboard_reconciler.go
  controllers/reconcilers/kserve_serverless_inferenceservice_reconciler.go
  controllers/resources/configmap.go
  controllers/suite_test.go
  controllers/testdata/deploy/kserve-openvino-serving-runtime-1.yaml
  main.go
Labels: approved, lgtm

#225 Added kserve dashboard metrics reconciler
  Containerfile
  controllers/comparators/configmap_comparator.go
  controllers/constants/caikit-metrics.json
  controllers/constants/constants.go
  controllers/constants/ovms-metrics.json
  controllers/constants/tgis-metrics.json
  controllers/constants/vllm-metrics.json
  controllers/inferenceservice_controller.go
  controllers/reconcilers/kserve_metrics_dashboard_reconciler.go
  controllers/reconcilers/kserve_serverless_inferenceservice_reconciler.go
  controllers/resources/configmap.go
  controllers/suite_test.go
  controllers/testdata/deploy/kserve-openvino-serving-runtime-1.yaml
  main.go
Labels: approved, lgtm

#229 Internal hostname gateway follow up
  controllers/inferenceservice_controller.go
  controllers/kserve_inferenceservice_controller_test.go
  controllers/reconcilers/kserve_isvc_gateway_reconciler.go
  controllers/reconcilers/kserve_isvc_service_cert_reconciler.go
Labels: approved, lgtm, rhods-2.11
