Repository opendatahub-io/odh-model-controller, pull requests merged in 2024-05, with the labels that each got.

#202 Modify Regular Expression for the support of tag suffix with latest/fast
  .github/workflows/create-release.yaml
Labels: approved, lgtm

#203 [RHOAIENG-6877] - odh-model-controller breaks Knative if KServe-Serve…
  Makefile
  config/webhook/field_patch.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  config/webhook/webhook_patch.yaml
Labels: approved, lgtm

#200 Refactor kserve metrics solution to work with prometheus annotations
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/constants/constants.go
  controllers/reconcilers/kserve_istio_peerauthentication_reconciler.go
  controllers/reconcilers/kserve_istio_podmonitor_reconciler.go
  controllers/reconcilers/kserve_istio_servicemonitor_reconciler.go
  controllers/reconcilers/kserve_metrics_service_reconciler.go
  controllers/reconcilers/kserve_metrics_servicemonitor_reconciler.go
  controllers/utils/utils.go
  main.go
Labels: approved, lgtm

#206 [RHOAIENG-7299] - Infinite loop in JSON unmarshaling in google.golang…
  go.mod
  go.sum
Labels: approved, lgtm

#205 [RHOAIENG-7299] - Infinite loop in JSON unmarshaling in google.golang…
  go.mod
  go.sum
Labels: approved, lgtm

#208 [release-0.12.0] Update params.env with current tag
  config/base/params.env
Labels: approved, lgtm

#189 Add runtime templates
  config/base/kustomization.yaml
  config/base/params.env
  config/default/kustomization.yaml
  config/overlays/odh/params.yaml
  config/runtimes/caikit-tgis-template.yaml
  config/runtimes/kustomization.yaml
  config/runtimes/ovms-kserve-template.yaml
  config/runtimes/ovms-mm-template.yaml
  config/runtimes/tgis-template.yaml
  config/runtimes/vllm-template.yaml
Labels: approved, lgtm, ok-to-test

#212 Sync release branch with main in preparation for RHOAI 2.10 release
  config/base/kustomization.yaml
  config/base/params.env
  config/default/kustomization.yaml
  config/overlays/odh/params.yaml
  config/runtimes/caikit-tgis-template.yaml
  config/runtimes/kustomization.yaml
  config/runtimes/ovms-kserve-template.yaml
  config/runtimes/ovms-mm-template.yaml
  config/runtimes/tgis-template.yaml
  config/runtimes/vllm-template.yaml
Labels: approved, lgtm

#214 bug: Webhook is blocked by networkpolicy
  config/default/kustomization.yaml
  config/default/networkpolicy.yaml
Labels: approved, lgtm

#215 Sync main -> release-0.12.0
  config/default/kustomization.yaml
  config/default/networkpolicy.yaml
  controllers/inferenceservice_controller.go
  controllers/utils/init.go
  controllers/utils/utils.go
  main.go
Labels: approved
