Repository opendatahub-io/odh-model-controller, pull requests merged in 2024-11, with the labels that each got.

#287 Add runtime template of vLLM ROCM
  config/base/kustomization.yaml
  config/base/params-vllm-rocm.env
  config/runtimes/kustomization.yaml
  config/runtimes/vllm-rocm-template.yaml
Labels: approved, lgtm

#284 [RHOAIENG-15386] add a new servingruntime vllm-multinode-template
  config/base/kustomization.yaml
  config/runtimes/kustomization.yaml
  config/runtimes/vllm-multinode-template.yaml
Labels: approved, lgtm

#290 Add runtime template of vLLM Gaudi
  config/base/kustomization.yaml
  config/base/params-vllm-gaudi.env
  config/runtimes/kustomization.yaml
  config/runtimes/vllm-gaudi-template.yaml
Labels: approved, lgtm

#285 Add runtime template of vLLM Gaudi
  config/base/kustomization.yaml
  config/base/params-vllm-gaudi.env
  config/runtimes/kustomization.yaml
  config/runtimes/vllm-gaudi-template.yaml
Labels: approved

#291 Fix ServingRuntime args
  config/runtimes/vllm-multinode-template.yaml
Labels: approved, lgtm

#292 [Cherry-Pick] vLLM multi-node template
  config/base/kustomization.yaml
  config/runtimes/kustomization.yaml
  config/runtimes/vllm-multinode-template.yaml
Labels: approved, lgtm

#293 [RHOAIENG-15763] Enhance probe to support rollingUpgrade
  config/runtimes/vllm-multinode-template.yaml
Labels: approved, lgtm

#294 [Cherry-Pick] Enhance probe to support rollingUpgrade (#293)
  config/runtimes/vllm-multinode-template.yaml
Labels: approved, lgtm

#288 Create webhook for NIM enablement
  PROJECT
  config/webhook/manifests.yaml
  config/webhook/webhook_patch.yaml
  controllers/suite_test.go
  controllers/webhook/nim_account_webhook.go
  controllers/webhook_nim_account_validator_test.go
  main.go
Labels: approved, lgtm, ok-to-test

#295 [RHOAIENG-15763] Enhance template not to use query for checking model health
  config/runtimes/vllm-multinode-template.yaml
Labels: approved

#289 Task/NVPE-10: Create NIM Account controller
  config/crd/external/kustomization.yaml
  config/crd/external/template.openshift.io_templates.yaml
  config/rbac/role.yaml
  controllers/constants/constants.go
  controllers/nim_account_controller.go
  controllers/nim_account_controller_test.go
  controllers/suite_test.go
  controllers/testdata/nim/ngc_catalog_response.json
  controllers/testdata/nim/ngc_model_llama-3_1-8b-instruct_response.json
  controllers/testdata/nim/ngc_model_phi-3-mini-4k-instruct_response.json
  controllers/testdata/nim/ngc_token_response.json
  controllers/testdata/nim/runtime_token_response.json
  controllers/testdata/nvidia_api_mock.go
  controllers/utils/conditions.go
  controllers/utils/init.go
  controllers/utils/nim.go
  hack/verify_nvidia_nim_api.go
  main.go
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#297 fix typo
  config/runtimes/vllm-multinode-template.yaml
Labels: approved

#298 [cherry-pick] fix typo
  config/runtimes/vllm-multinode-template.yaml
Labels: approved

#301 fix: nim configmap name
  controllers/constants/constants.go
Labels: approved, lgtm, needs-ok-to-test

#300 [RHOAIENG-15207] Removed the $(mesh_namespace) variable from manifests
  config/base/kustomization.yaml
  config/rbac/role_binding.yaml
Labels: approved, lgtm

#299 Update caikit-tgis and ovms stable image
  config/base/params.env
Labels: approved, lgtm

#305 fix: fetching gvk from scheme requires error handling
  controllers/nim_account_controller.go
  controllers/utils/nim.go
Labels: approved, lgtm, needs-ok-to-test

#304 Pin vLLM images for Gaudi and ROCM
  config/base/params-vllm-gaudi.env
  config/base/params-vllm-rocm.env
Labels: approved

#306 fix: dashboard require an existing array of supported models in the s…
  controllers/utils/nim.go
Labels: approved, lgtm, needs-ok-to-test

#302 Sync main -> release-0.12.0: Preparing ODH release
  Containerfile
  PROJECT
  api/nim/v1/account_types.go
  api/nim/v1/groupversion_info.go
  api/nim/v1/zz_generated.deepcopy.go
  config/base/kustomization.yaml
  config/crd/bases/nim.opendatahub.io_accounts.yaml
  config/crd/external/kustomization.yaml
  config/crd/external/template.openshift.io_templates.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/overlays/odh/params.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/webhook_patch.yaml
  controllers/constants/constants.go
  controllers/nim_account_controller.go
  controllers/nim_account_controller_test.go
  controllers/suite_test.go
  controllers/testdata/nim/ngc_catalog_response.json
  controllers/testdata/nim/ngc_model_llama-3_1-8b-instruct_response.json
  controllers/testdata/nim/ngc_model_phi-3-mini-4k-instruct_response.json
  controllers/testdata/nim/ngc_token_response.json
  controllers/testdata/nim/runtime_token_response.json
  controllers/testdata/nvidia_api_mock.go
  controllers/utils/conditions.go
  controllers/utils/init.go
  controllers/utils/nim.go
  controllers/webhook/nim_account_webhook.go
  controllers/webhook_nim_account_validator_test.go
  hack/verify_nvidia_nim_api.go
  main.go
Labels: approved

#308 update global ca bundle logic and storage-config logic
  controllers/kserve_customcacert_controller.go
  controllers/kserve_customcacert_controller_test.go
  controllers/storageconfig_controller.go
  controllers/storageconfig_controller_test.go
  controllers/suite_test.go
  go.mod
Labels: approved, lgtm

#309 [Cherry-Pick] update global ca bundle logic and storage-config logic
  controllers/kserve_customcacert_controller.go
  controllers/kserve_customcacert_controller_test.go
  controllers/storageconfig_controller.go
  controllers/storageconfig_controller_test.go
  controllers/suite_test.go
  go.mod
Labels: approved

#318 [RHOAIENG-16263]Disable dashboard and fix servingruntime display name
  config/runtimes/vllm-multinode-template.yaml
Labels: approved, lgtm

#316 Use the main branch to build stable image tags, incubating for latest…
  .github/workflows/build.yaml
  .github/workflows/verify-odh-model-controller-img-tag.yaml
Labels: approved, lgtm

#311 [RHOAIENG-13638] - Do not allow isvc creation in protected isvc
  config/base/params.env
  config/webhook/manifests.yaml
  config/webhook/webhook_patch.yaml
  controllers/kserve_inferenceservice_controller_metrics_test.go
  controllers/storageconfig_controller_test.go
  controllers/utils/utils.go
  controllers/webhook/isvc_validator.go
  controllers/webhook/ksvc_validator.go
  controllers/webhook/nim_account_webhook.go
  controllers/webhook_isvc_validator_test.go
  controllers/webhook_ksvc_validator_test.go
  main.go
Labels: approved, lgtm

#322 small changes on git action
  .github/workflows/build.yaml
  .github/workflows/verify-odh-model-controller-img-tag.yaml
Labels: approved, lgtm

#323 [Cherry-Pick] update gitaction based on branch strategy change (#322)
  .github/workflows/build.yaml
  .github/workflows/verify-odh-model-controller-img-tag.yaml
Labels: approved, lgtm

#315 Use the stable image tags on the main branch
  config/base/params.env
Labels: approved, lgtm
