Repository opendatahub-io/odh-model-controller, pull requests merged in 2024-08, with the labels that each got.

#247 Update ENVTEST_K8S_VERSION for s390x
  Makefile
Labels: approved, lgtm, ok-to-test

#253 Updated kustomize labels to kustomize v5 syntax
  config/base/kustomization.yaml
  config/default/kustomization.yaml
  config/overlays/dev/kustomization.yaml
  config/overlays/odh/kustomization.yaml
  config/rbac/role_binding.yaml
  config/runtimes/kustomization.yaml
Labels: approved, lgtm

#255 Use a more fine-grained SAR for Authorino
  controllers/resources/authconfig.go
  controllers/resources/template/authconfig_userdefined.yaml
Labels: approved

#260 Use a more fine-grained SAR for Authorino
  controllers/resources/authconfig.go
  controllers/resources/template/authconfig_userdefined.yaml
Labels: approved, lgtm

#256 [RHOAIENG-11527] - [backend] Incorrect values for number of requests …
  controllers/constants/constants.go
  controllers/constants/runtime-metrics.go
  controllers/kserve_inferenceservice_controller_metrics_test.go
  controllers/reconcilers/kserve_metrics_dashboard_reconciler.go
  controllers/utils/utils.go
Labels: approved, lgtm

#261 Cherry-pick https://github.com/opendatahub-io/odh-model-controller/pull/256
  controllers/constants/constants.go
  controllers/constants/runtime-metrics.go
  controllers/kserve_inferenceservice_controller_metrics_test.go
  controllers/reconcilers/kserve_metrics_dashboard_reconciler.go
  controllers/utils/utils.go
Labels: approved, lgtm

#251 Ensure functions use inherited context
  controllers/reconcilers/kserve_authconfig_reconciler.go
Labels: approved, lgtm

#254 RHOAIENG-1044: Update hardcoded constants as environment variables
  Makefile
  controllers/constants/constants.go
  controllers/kserve_inferenceservice_controller_authconfig_test.go
  controllers/kserve_inferenceservice_controller_mesh_test.go
  controllers/kserve_inferenceservice_controller_test.go
  controllers/reconcilers/kserve_route_reconciler.go
  controllers/suite_test.go
  controllers/utils/utils.go
  controllers/webhook/ksvc_validator.go
  controllers/webhook_ksvc_validator_test.go
Labels: approved, lgtm, jira/valid-reference
