Repository opendatahub-io/odh-model-controller, pull requests merged in 2025-01, with the labels that each got.

#340 chore: use naming convention for resources created by nim
  internal/controller/constants/constants.go
  internal/controller/nim/account_controller.go
  internal/controller/nim/account_controller_test.go
Labels: approved, lgtm, ok-to-test

#344 chore: set nim runtime api call page size to 1000
  internal/controller/utils/nim.go
Labels: approved, lgtm, ok-to-test

#342 Nim enablement change default to managed and add clean up job
  cmd/main.go
  config/base/params.env
  internal/controller/utils/nim.go
Labels: approved, lgtm, ok-to-test

#343 Update ovms to current build
  config/base/params.env
Labels: approved, lgtm

#345 Authorization for InferenceGraph (Serverless)
  PROJECT
  cmd/main.go
  config/crd/external/authorino.kuadrant.io_authconfigs.yaml
  config/crd/external/serving.kserve.io_inferencegraphs.yaml
  config/rbac/role.yaml
  internal/controller/constants/constants.go
  internal/controller/resources/authconfig.go
  internal/controller/resources/authconfig_test.go
  internal/controller/resources/template/authconfig_inferencegraph_userdefined.yaml
  internal/controller/resources/template/authconfig_isvc_userdefined.yaml
  internal/controller/serving/inferencegraph_controller.go
  internal/controller/serving/inferencegraph_controller_test.go
  internal/controller/serving/inferenceservice_controller_test.go
  internal/controller/serving/reconcilers/kserve_authconfig_reconciler.go
  internal/controller/serving/suite_test.go
Labels: approved, lgtm

#347 [RHOAIENG-10293] add metrics resources for rawdeployment
  config/crd/external/serving.kserve.io_servingruntimes.yaml
  internal/controller/serving/inferenceservice_controller_test.go
  internal/controller/serving/reconcilers/kserve_metrics_dashboard_reconciler.go
  internal/controller/serving/reconcilers/kserve_metrics_service_reconciler.go
  internal/controller/serving/reconcilers/kserve_metrics_servicemonitor_reconciler.go
  internal/controller/serving/reconcilers/kserve_raw_inferenceservice_reconciler.go
  internal/controller/serving/reconcilers/kserve_serverless_inferenceservice_reconciler.go
  internal/controller/utils/utils.go
Labels: approved, lgtm

#341 [RHOAIENG-16851] rawdeployment route bug fixes
  internal/controller/serving/reconcilers/kserve_raw_route_reconciler.go
Labels: approved, lgtm

#354 Fix CVE-2024-45338
  go.mod
  go.sum
Labels: approved

#355 [Cherry-Pick] Fix CVE-2024-45338
  go.mod
  go.sum
Labels: approved

#356 Update all runtime stable images
  config/base/params-vllm-gaudi.env
  config/base/params-vllm-rocm.env
  config/base/params.env
  config/component_metadata.yaml
Labels: approved, lgtm

#358 Fix for ModelMesh-only setups - Start InferenceGraph controller only if the CRD is present
  cmd/main.go
Labels: approved, lgtm

#357 Prevent InferenceGraphs to refer to other namespaces
  PROJECT
  cmd/main.go
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  internal/webhook/serving/v1alpha1/inferencegraph_webhook.go
  internal/webhook/serving/v1alpha1/inferencegraph_webhook_test.go
Labels: approved, lgtm
