Repository opendatahub-io/odh-model-controller, pull requests merged in 2025-05, with the labels that each got.

#422 add powerz mentions in vllm cpu template
  config/runtimes/vllm-cpu-template.yaml
Labels: approved, lgtm, ok-to-test

#427 revert previous pull request to add vLLM cpu template
  config/runtimes/vllm-cpu-template.yaml
Labels: approved, lgtm, ok-to-test

#429 fix(make): ensures tools are always in the correct version
  Makefile
Labels: approved, lgtm

#424 upgrade to go 1.23
  Containerfile
  go.mod
Labels: approved, lgtm

#448 add repo specific PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm

#447 RHOAIENG-25652: Bump KServe to 0.15
  config/crd/external/serving.kserve.io_inferencegraphs.yaml
  config/crd/external/serving.kserve.io_inferenceservices.yaml
  config/crd/external/serving.kserve.io_servingruntimes.yaml
  go.mod
  go.sum
  internal/controller/serving/reconcilers/kserve_route_reconciler.go
Labels: approved, lgtm, jira/valid-reference

#449 Aggregate code coverage for `make test`
  Makefile
Labels: approved, lgtm

#450 Consistent and automated KServe CRDs download
  Makefile
  config/crd/external/.kserve_manifests_revision
Labels: approved, lgtm

#451 Add bartoszmajsak and pierDipi to OWNERS
  OWNERS
Labels: approved, lgtm

#446 chore: updated the account api print columns
  api/nim/v1/account_types.go
  config/crd/bases/nim.opendatahub.io_accounts.yaml
Labels: approved, lgtm, ok-to-test

#459 [RHOAIENG-25522] Route that is not managed by the InferenceService gets deleted
  internal/controller/serving/inferenceservice_controller_test.go
  internal/controller/serving/reconcilers/kserve_route_reconciler.go
Labels: approved, lgtm

#444 fix: model selection should update the account status for failurs
  internal/controller/nim/handlers/configmap_handler.go
  internal/controller/nim/handlers/handlers.go
  internal/controller/nim/handlers/validation_handler.go
  internal/controller/utils/nim.go
Labels: approved, lgtm, ok-to-test

#452 RHOAIENG-25111: Add KEDA reconciler for raw deployment mode
  config/crd/external/keda.sh_triggerauthentications.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/serving/inferenceservice_controller.go
  internal/controller/serving/inferenceservice_controller_test.go
  internal/controller/serving/keda_fixtures_test.go
  internal/controller/serving/reconcilers/kserve_keda_reconciler.go
  internal/controller/serving/reconcilers/kserve_raw_inferenceservice_reconciler.go
  internal/controller/serving/reconcilers/meta.go
  internal/controller/utils/init.go
  test/matchers/gomega_uid_matcher.go
Labels: approved, lgtm, jira/valid-reference

#463 Separate HF Detector into its own params.env file
  config/base/kustomization.yaml
  config/base/params-guardrails-hf-runtime.env
  config/base/params.env
Labels: lgtm

#467 Sync/250528 incubation main
  .github/PULL_REQUEST_TEMPLATE.md
  Containerfile
  Makefile
  OWNERS
  api/nim/v1/account_types.go
  config/crd/bases/nim.opendatahub.io_accounts.yaml
  config/crd/external/.kserve_manifests_revision
  config/crd/external/serving.kserve.io_inferencegraphs.yaml
  config/crd/external/serving.kserve.io_inferenceservices.yaml
  config/crd/external/serving.kserve.io_servingruntimes.yaml
  config/runtimes/vllm-cpu-template.yaml
  go.mod
  go.sum
  internal/controller/serving/reconcilers/kserve_route_reconciler.go
Labels: approved, lgtm, tide/merge-method-merge
