Repository opendatahub-io/odh-model-controller, pull requests merged in 2025-04, with the labels that each got.

#400 Update approvers in owners file with runtimes team members
  OWNERS
Labels: approved, lgtm

#404 correct tgis deprecation changes
  config/base/kustomization.yaml
  config/base/params.env
Labels: approved, lgtm

#408 Sync/250408 incubation main
  Containerfile
  OWNERS
  api/nim/v1/account_types.go
  api/nim/v1/zz_generated.deepcopy.go
  cmd/main.go
  config/base/kustomization.yaml
  config/base/params.env
  config/crd/bases/nim.opendatahub.io_accounts.yaml
  config/runtimes/kustomization.yaml
  config/runtimes/tgis-template.yaml
  config/runtimes/vllm-cuda-template.yaml
  config/runtimes/vllm-gaudi-template.yaml
  config/runtimes/vllm-multinode-template.yaml
  config/runtimes/vllm-rocm-template.yaml
  hack/verify_nvidia_nim_api.go
  internal/controller/nim/account_controller.go
  internal/controller/nim/account_controller_test.go
  internal/controller/serving/testdata/configmaps/odh-model-controller-parameters.yaml
  internal/controller/utils/nim.go
Labels: approved, lgtm, tide/merge-method-merge

#409 New automerge gitaction
  .github/workflows/prow-merge-incubating-with-main.yaml
Labels: approved, lgtm

#410 Restore code removed by mistake
  cmd/main.go
  internal/controller/serving/inferenceservice_controller.go
  internal/controller/serving/suite_test.go
Labels: approved, lgtm

#413 Adding Both Custom and Trusted Certs to Kserve CA Configmap
  internal/controller/constants/constants.go
  internal/controller/core/configmap_controller.go
  internal/controller/core/configmap_controller_test.go
  internal/controller/core/secret_controller.go
  internal/controller/core/secret_controller_test.go
  internal/controller/core/testdata/configmaps/odh-kserve-custom-ca-cert-configmap-updated.yaml
  internal/controller/core/testdata/configmaps/odh-kserve-custom-ca-cert-configmap.yaml
  internal/controller/core/testdata/configmaps/odh-trusted-ca-bundle-configmap-updated.yaml
  internal/controller/core/testdata/configmaps/odh-trusted-ca-bundle-configmap.yaml
  internal/controller/core/testdata/secrets/storageconfig-cert-encoded.yaml
  internal/controller/core/testdata/secrets/storageconfig-updated-cert-encoded.yaml
Labels: approved, lgtm

#415 [Cherry-Pick]Restore code removed by mistake (#410)
  cmd/main.go
  internal/controller/serving/inferenceservice_controller.go
  internal/controller/serving/suite_test.go
Labels: approved, lgtm

#416 Add volume to servingRuntime template
  internal/controller/utils/nim.go
Labels: approved, lgtm, needs-ok-to-test

#417 [Cherry-pick] Add volume to servingRuntime template (#416)
  internal/controller/utils/nim.go
Labels: approved, lgtm, needs-ok-to-test

#418 Extract runtime image reference from params.env file
  config/base/kustomization.yaml
  config/base/params-cuda.env
  config/base/params.env
Labels: approved, lgtm

#420 :sparkles: added huggingface detector runtime template (#412)
  config/base/kustomization.yaml
  config/base/params.env
  config/runtimes/hf-detector-template.yaml
  config/runtimes/kustomization.yaml
Labels: approved, lgtm
