Repository opendatahub-io/odh-model-controller, pull requests merged in 2025-03, with the labels that each got.

#385 ODH v2.25 sync with main
  .gitignore
  OWNERS
  PROJECT
  cmd/main.go
  config/base/kustomization.yaml
  config/base/params.env
  config/manager/manager.yaml
  config/rbac/role.yaml
  config/runtimes/vllm-multinode-template.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  dev_tools/devspace.yaml
  dev_tools/devspace_start.sh
  go.mod
  internal/controller/constants/constants.go
  internal/controller/core/pod_controller.go
  internal/controller/core/pod_controller_test.go
  internal/controller/core/secret_controller.go
  internal/controller/nim/account_controller.go
  internal/controller/serving/inferenceservice_controller.go
  internal/controller/serving/inferenceservice_controller_test.go
  internal/controller/serving/reconcilers/kserve_istio_smm_reconciler.go
  internal/controller/serving/reconcilers/kserve_raw_clusterrolebinding_reconciler.go
  internal/controller/serving/reconcilers/kserve_raw_inferenceservice_reconciler.go
  internal/controller/serving/reconcilers/kserve_serverless_inferenceservice_reconciler.go
  internal/controller/serving/reconcilers/mm_inferenceservice_reconciler.go
  internal/controller/serving/servingruntime_controller.go
  internal/controller/serving/servingruntime_controller_test.go
  internal/controller/serving/suite_test.go
  internal/controller/serving/testdata/deploy/vllm-multinode-servingruntime.yaml
  internal/controller/utils/cert.go
  internal/controller/utils/cert_test.go
  internal/controller/utils/utils.go
  internal/webhook/core/v1/pod_webhook.go
  internal/webhook/core/v1/pod_webhook_test.go
  internal/webhook/core/v1/webhook_suite_test.go
Labels: approved, lgtm

#387 Fix the ODH 2.25 sync so it is not squashed
  config/base/params.env
Labels: approved

#369 feat(mr): re-enable model registry reconciler and add svc annotation to it
  cmd/main.go
  config/base/kustomization.yaml
  config/base/odh_model_controller_manager_patch.yaml
  config/base/params.env
  config/manager/manager.yaml
  go.mod
  go.sum
  internal/controller/constants/constants.go
  internal/controller/serving/inferenceservice_controller.go
  internal/controller/serving/reconcilers/model_registry_reconciler.go
Labels: approved, lgtm

#383 chore: added logs for nim api responses
  hack/verify_nvidia_nim_api.go
  internal/controller/nim/account_controller.go
  internal/controller/utils/nim.go
Labels: approved, lgtm, needs-ok-to-test

#384 chore: filter events for the nim controller
  internal/controller/nim/account_controller.go
Labels: approved, lgtm, needs-ok-to-test

#388 Move arguments from 'args' to 'command' for vllm multinode SR
  config/runtimes/vllm-multinode-template.yaml
Labels: approved, lgtm

#390 fix: legally blocked content should not break NIM integration
  hack/verify_nvidia_nim_api.go
  internal/controller/nim/account_controller.go
  internal/controller/nim/account_controller_test.go
  internal/controller/nim/testdata/ngc_catalog_response_page_0.json
  internal/controller/nim/testdata/ngc_catalog_response_page_1.json
  internal/controller/utils/nim.go
Labels: approved, lgtm, needs-ok-to-test

#372 Updating README and adding devspace README
  README.md
  dev_tools/README.md
Labels: approved, lgtm

#397 ODH 2.26 sync
  README.md
  cmd/main.go
  config/base/kustomization.yaml
  config/base/odh_model_controller_manager_patch.yaml
  config/base/params.env
  config/manager/manager.yaml
  config/runtimes/vllm-multinode-template.yaml
  config/webhook/kustomization.yaml
  dev_tools/README.md
  go.mod
  go.sum
  hack/verify_nvidia_nim_api.go
  internal/controller/constants/constants.go
  internal/controller/nim/account_controller.go
  internal/controller/nim/account_controller_test.go
  internal/controller/nim/testdata/ngc_catalog_response_page_0.json
  internal/controller/nim/testdata/ngc_catalog_response_page_1.json
  internal/controller/resources/authconfig.go
  internal/controller/serving/inferencegraph_controller_test.go
  internal/controller/serving/inferenceservice_controller.go
  internal/controller/serving/inferenceservice_controller_test.go
  internal/controller/serving/reconcilers/kserve_raw_clusterrolebinding_reconciler.go
  internal/controller/serving/reconcilers/kserve_raw_route_reconciler.go
  internal/controller/serving/reconcilers/model_registry_reconciler.go
  internal/controller/serving/testdata/configmaps/odh-model-controller-parameters.yaml
  internal/controller/utils/nim.go
  internal/webhook/core/v1/pod_webhook.go
  internal/webhook/core/v1/pod_webhook_test.go
Labels: approved

#398 [RHOAIENG-20597] vLLM Serving Runtime Template naming changes
  config/base/kustomization.yaml
  config/base/params.env
  config/runtimes/kustomization.yaml
  config/runtimes/vllm-cuda-template.yaml
  config/runtimes/vllm-gaudi-template.yaml
  config/runtimes/vllm-multinode-template.yaml
  config/runtimes/vllm-rocm-template.yaml
  internal/controller/serving/testdata/configmaps/odh-model-controller-parameters.yaml
Labels: approved, lgtm, ok-to-test

#401 fix: TGIS image removal not completely done
  config/base/kustomization.yaml
  internal/controller/serving/testdata/configmaps/odh-model-controller-parameters.yaml
Labels: approved, lgtm

#402 chore: nim account controller should trigger all secret changes
  internal/controller/nim/account_controller.go
Labels: approved, lgtm, ok-to-test

#403 chore: nim account controller should trigger all secret changes
  internal/controller/nim/account_controller.go
Labels: approved, lgtm, needs-ok-to-test

#391 chore: nim setup should use the setup logger
  cmd/main.go
  internal/controller/nim/account_controller.go
Labels: approved, lgtm, ok-to-test

#392 chore: refactor hack script for verifying nim integration
  hack/verify_nvidia_nim_api.go
Labels: approved, lgtm, ok-to-test
