Repository opendatahub-io/odh-model-controller, pull requests merged in 2025-02, with the labels that each got.

#362 fix: added accept header to nim manifest pull requests accepting oci
  internal/controller/testdata/nvidia_api_mock.go
  internal/controller/utils/nim.go
Labels: approved, lgtm, needs-ok-to-test

#361 Fix: Ensure odh-model-controller Deployment Waits for ConfigMap
  cmd/main.go
  config/manager/manager.yaml
Labels: approved, lgtm, ok-to-test

#363 fix: nim containers terminated prematurely
  internal/controller/utils/nim.go
Labels: approved, lgtm, ok-to-test

#367 fix: cherry picking appeng fixes for 2.18
  cmd/main.go
  config/manager/manager.yaml
  internal/controller/testdata/nvidia_api_mock.go
  internal/controller/utils/nim.go
Labels: approved, lgtm, ok-to-test

#365 [RHOAIENG-16435] Fixed error that was caused when deleting an ISVC using RawDeployment and ServiceMesh is not installed
  internal/controller/serving/inferenceservice_controller.go
  internal/controller/serving/reconcilers/kserve_serverless_inferenceservice_reconciler.go
Labels: approved, lgtm

#346 [RHOAIENG-13566] Configure SSL for the communication between head and worker
  PROJECT
  cmd/main.go
  config/runtimes/vllm-multinode-template.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  go.mod
  internal/controller/constants/constants.go
  internal/controller/core/pod_controller.go
  internal/controller/core/pod_controller_test.go
  internal/controller/core/secret_controller.go
  internal/controller/serving/inferenceservice_controller.go
  internal/controller/serving/servingruntime_controller.go
  internal/controller/serving/servingruntime_controller_test.go
  internal/controller/serving/suite_test.go
  internal/controller/serving/testdata/deploy/vllm-multinode-servingruntime.yaml
  internal/controller/utils/cert.go
  internal/controller/utils/cert_test.go
  internal/controller/utils/utils.go
  internal/webhook/core/v1/pod_webhook.go
  internal/webhook/core/v1/pod_webhook_test.go
  internal/webhook/core/v1/webhook_suite_test.go
Labels: approved, lgtm

#366 Adding devspace files
  .gitignore
  dev_tools/devspace.yaml
  dev_tools/devspace_start.sh
Labels: approved, lgtm

#359 Move kserve and MM release metadata to corresponding repos
  config/component_metadata.yaml
Labels: approved, lgtm

#370 2/13/2025 Sync main with ODH v2.24
  PROJECT
  cmd/main.go
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  internal/webhook/serving/v1alpha1/inferencegraph_webhook.go
  internal/webhook/serving/v1alpha1/inferencegraph_webhook_test.go
Labels: approved, lgtm

#371 [Not squashed version] 2/13/2025 Sync main with ODH v2.24
  config/base/params.env
Labels: approved

#368 fix: cleanup fails for disabled NIM
  cmd/main.go
  internal/controller/utils/nim.go
  internal/controller/utils/nim_test.go
  internal/controller/utils/suite_test.go
Labels: approved, lgtm, ok-to-test

#374 add kserve-state and modelmesh-state as args
  cmd/main.go
  config/base/kustomization.yaml
  config/base/params.env
  config/manager/manager.yaml
Labels: approved, lgtm

#364 only create CRB for raw if isvc has auth
  config/rbac/role.yaml
  internal/controller/constants/constants.go
  internal/controller/serving/inferenceservice_controller.go
  internal/controller/serving/inferenceservice_controller_test.go
  internal/controller/serving/reconcilers/kserve_istio_smm_reconciler.go
  internal/controller/serving/reconcilers/kserve_raw_clusterrolebinding_reconciler.go
  internal/controller/serving/reconcilers/kserve_raw_inferenceservice_reconciler.go
  internal/controller/serving/reconcilers/kserve_serverless_inferenceservice_reconciler.go
  internal/controller/serving/reconcilers/mm_inferenceservice_reconciler.go
Labels: approved, lgtm

#376 adding brettmthompson as approver and reviewer in OWNERS file
  OWNERS
Labels: approved, lgtm

#378 [RHOAIENG-20323] fix condition in multi-node servingruntime
  config/runtimes/vllm-multinode-template.yaml
Labels: approved, lgtm

#360 Update status post frequency for NIM account controller
  internal/controller/nim/account_controller.go
Labels: approved, lgtm, ok-to-test

#375 Update OWNERS
  OWNERS
Labels: approved, lgtm

#377 fix: when in Raw Mode as no Authorino is available, should not own AuthConfig
  cmd/main.go
  internal/controller/serving/inferencegraph_controller.go
  internal/controller/serving/suite_test.go
Labels: approved, lgtm

#379 [Cherry-Pick:377] fix: when in Raw Mode as no Authorino is available, should not own
  cmd/main.go
  internal/controller/serving/inferencegraph_controller.go
  internal/controller/serving/suite_test.go
Labels: approved, lgtm

#382 Use annotation instead of label to enable auth for RawDeployment
  internal/controller/constants/constants.go
  internal/controller/resources/authconfig.go
  internal/controller/serving/inferencegraph_controller_test.go
  internal/controller/serving/inferenceservice_controller_test.go
  internal/controller/serving/reconcilers/kserve_raw_clusterrolebinding_reconciler.go
  internal/controller/serving/reconcilers/kserve_raw_route_reconciler.go
Labels: approved, lgtm

#381 Add an image to params.env for init container for ray-tls-generator
  config/base/params.env
  internal/controller/serving/testdata/configmaps/odh-model-controller-parameters.yaml
  internal/webhook/core/v1/pod_webhook.go
  internal/webhook/core/v1/pod_webhook_test.go
Labels: approved, lgtm

#380 revert: revert "Update status post frequency for NIM account controll…
  internal/controller/nim/account_controller.go
Labels: approved, lgtm, ok-to-test
